# -*- coding: utf-8 -*-
"""Validate UTF-8 JSON outputs generated by the art pipeline."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parents[1]


CHECKS = [
    {
        "name": "integration_candidates",
        "path": "美术文档/_generated/可接入素材清单.json",
        "summary": [
            ("program_integrate", ("Summary", "ActionCounts", "program_integrate")),
            ("generate_needed", ("Summary", "ActionCounts", "generate_needed"), 0),
        ],
    },
    {
        "name": "program_handoff",
        "path": "美术文档/_generated/程序接入交接清单.json",
        "summary": [
            ("program_integrate", ("Summary", "ProgramIntegrateVisualCount")),
            ("rerun_acceptance", ("Summary", "ProgramRerunAcceptanceScreenCount")),
            ("add_capture", ("Summary", "ProgramAddCaptureScreenCount")),
        ],
    },
    {
        "name": "quality_backlog",
        "path": "美术文档/_generated/素材质量替换清单.json",
        "summary": [
            ("technical_fix", ("Summary", "ActionCounts", "technical_fix"), 0),
            ("visual_v2_replace", ("Summary", "ActionCounts", "visual_v2_replace"), 0),
            ("spec_review", ("Summary", "ActionCounts", "spec_review"), 0),
        ],
    },
    {
        "name": "requirement_candidates",
        "path": "美术文档/_generated/美术需求候选清单.json",
        "summary": [
            ("new_candidate", ("Summary", "StatusCounts", "new_candidate"), 0),
            ("deferred_candidate", ("Summary", "StatusCounts", "deferred_candidate"), 0),
            ("ignored_candidate", ("Summary", "StatusCounts", "ignored_candidate"), 0),
        ],
    },
    {
        "name": "formal_v2_asset_review",
        "path": "美术文档/_generated/formal_v2_asset_review/formal_v2_asset_review.json",
        "summary": [
            ("reviewed", ("Summary", "ReviewedVisualCount")),
            ("pass", ("Summary", "ReviewStatusCounts", "pass")),
            ("all_pass", ("Summary", "AllPass")),
        ],
    },
    {
        "name": "formal_v2_prompt_readiness",
        "path": "美术文档/_generated/formal_v2_prompt_readiness/formal_v2_prompt_readiness.json",
        "summary": [
            ("program_integrate", ("Summary", "ProgramIntegrateVisualCount")),
            ("prompt_ready", ("Summary", "PromptReadyCount")),
            ("prompt_blocked", ("Summary", "PromptBlockedCount")),
            ("generic_remaining", ("Summary", "GenericPromptRemainingCount")),
        ],
    },
    {
        "name": "registry_gap_checklist",
        "path": "美术文档/_generated/VisualAssetRegistry登记缺口清单.json",
        "summary": [
            ("program_integrate", ("Summary", "ProgramIntegrateVisualCount")),
            ("missing_registry", ("Summary", "MissingRegistryCount")),
            ("missing_approved", ("Summary", "MissingApprovedFileCount")),
            ("missing_meta", ("Summary", "MissingMetaFileCount")),
        ],
    },
]


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def dig(data: Any, keys: tuple[str, ...]) -> Any:
    current = data
    for key in keys:
        if not isinstance(current, dict) or key not in current:
            return None
        current = current[key]
    return current


def validate_one(check: dict[str, Any], strict: bool) -> tuple[bool, str]:
    path = PROJECT_ROOT / check["path"]
    if not path.exists():
        message = f"[MISS] {check['name']}: {check['path']}"
        return (not strict, message)

    try:
        data = read_json(path)
    except Exception as exc:  # noqa: BLE001 - CLI should report exact parser failure.
        return False, f"[FAIL] {check['name']}: JSON parse failed: {exc}"

    values: list[str] = []
    ok = True
    for item in check.get("summary", []):
        label = item[0]
        keys = tuple(item[1])
        default = item[2] if len(item) > 2 else None
        value = dig(data, keys)
        if value is None and default is not None:
            value = default
        if value is None:
            ok = False
            values.append(f"{label}=MISSING")
        else:
            values.append(f"{label}={value}")

    status = "OK" if ok else "FAIL"
    return ok, f"[{status}] {check['name']}: " + ", ".join(values)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--strict", action="store_true", help="Treat missing optional outputs as failures.")
    args = parser.parse_args()

    failed = False
    for check in CHECKS:
        ok, message = validate_one(check, strict=args.strict)
        print(message)
        failed = failed or not ok
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
