# -*- coding: utf-8 -*-
"""Validate UTF-8 JSON outputs generated by the art pipeline."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parents[1]


CHECKS = [
    {
        "name": "integration_candidates",
        "path": "美术文档/_generated/可接入素材清单.json",
        "summary": [
            ("program_integrate", ("Summary", "ActionCounts", "program_integrate"), 0),
            ("generate_needed", ("Summary", "ActionCounts", "generate_needed"), 0),
        ],
    },
    {
        "name": "program_handoff",
        "path": "美术文档/_generated/程序接入交接清单.json",
        "summary": [
            ("program_integrate", ("Summary", "ProgramIntegrateVisualCount")),
            ("rerun_acceptance", ("Summary", "ProgramRerunAcceptanceScreenCount")),
            ("add_capture", ("Summary", "ProgramAddCaptureScreenCount")),
        ],
    },
    {
        "name": "quality_backlog",
        "path": "美术文档/_generated/素材质量替换清单.json",
        "summary": [
            ("technical_fix", ("Summary", "ActionCounts", "technical_fix"), 0),
            ("visual_v2_replace", ("Summary", "ActionCounts", "visual_v2_replace"), 0),
            ("spec_review", ("Summary", "ActionCounts", "spec_review"), 0),
        ],
    },
    {
        "name": "requirement_candidates",
        "path": "美术文档/_generated/美术需求候选清单.json",
        "summary": [
            ("new_candidate", ("Summary", "StatusCounts", "new_candidate"), 0),
            ("deferred_candidate", ("Summary", "StatusCounts", "deferred_candidate"), 0),
            ("ignored_candidate", ("Summary", "StatusCounts", "ignored_candidate"), 0),
        ],
    },
    {
        "name": "formal_v2_asset_review",
        "path": "美术文档/_generated/formal_v2_asset_review/formal_v2_asset_review.json",
        "summary": [
            ("reviewed", ("Summary", "ReviewedVisualCount")),
            ("pass", ("Summary", "ReviewStatusCounts", "pass")),
            ("all_pass", ("Summary", "AllPass")),
        ],
    },
    {
        "name": "formal_v2_visual_semantic_review",
        "path": "美术文档/_generated/formal_v2_asset_review/visual_semantic_review.json",
        "summary": [
            ("reviewed", ("ReviewScope", "ReviewedVisualCount")),
            ("decision", ("Summary", "ProgramIntegrationDecision")),
            ("secondary_replacement_candidate", ("Summary", "VisualSemanticRiskCounts", "secondary_replacement_candidate"), 0),
            ("watch_runtime_readability", ("Summary", "VisualSemanticRiskCounts", "watch_runtime_readability"), 0),
        ],
    },
    {
        "name": "formal_v2_prompt_readiness",
        "path": "美术文档/_generated/formal_v2_prompt_readiness/formal_v2_prompt_readiness.json",
        "summary": [
            ("program_integrate", ("Summary", "ProgramIntegrateVisualCount")),
            ("prompt_ready", ("Summary", "PromptReadyCount")),
            ("prompt_blocked", ("Summary", "PromptBlockedCount")),
            ("generic_remaining", ("Summary", "GenericPromptRemainingCount")),
        ],
    },
    {
        "name": "registry_gap_checklist",
        "path": "美术文档/_generated/VisualAssetRegistry登记缺口清单.json",
        "summary": [
            ("program_integrate", ("Summary", "ProgramIntegrateVisualCount")),
            ("missing_registry", ("Summary", "MissingRegistryCount")),
            ("missing_approved", ("Summary", "MissingApprovedFileCount")),
            ("missing_meta", ("Summary", "MissingMetaFileCount")),
        ],
    },
    {
        "name": "formal_v2_runtime_acceptance_status",
        "path": "美术文档/_generated/FormalV2运行时验收状态.json",
        "summary": [
            ("gate", ("Gate",)),
            ("program_integrate", ("Summary", "ProgramIntegrateVisualCount")),
            ("missing_registry", ("Summary", "MissingRegistryCount")),
            ("run_id", ("Summary", "ReportRunID")),
            ("status", ("Summary", "ReportStatus")),
        ],
    },
    {
        "name": "formal_v2_runtime_review_queue",
        "path": "\u7f8e\u672f\u6587\u6863/_generated/FormalV2\u8fd0\u884c\u65f6\u590d\u9a8c\u4f18\u5148\u7ea7\u6e05\u5355.json",
        "summary": [
            ("gate", ("Summary", "RuntimeGate")),
            ("program_integrate", ("Summary", "ProgramIntegrateVisualCount")),
            ("missing_registry", ("Summary", "MissingRegistryCount")),
            ("review_queue", ("Summary", "ReviewQueueCount")),
        ],
    },
]


OFFLINE_REGISTRY_CANDIDATE = "美术文档/_generated/VisualAssetRegistry.offline_candidate.asset"
REGISTRY_GAP_CHECKLIST = "美术文档/_generated/VisualAssetRegistry登记缺口清单.json"
LIVE_REGISTRY_ASSET = "UnityClient/Assets/Resources/VisualAssetRegistry.asset"


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def dig(data: Any, keys: tuple[str, ...]) -> Any:
    current = data
    for key in keys:
        if not isinstance(current, dict) or key not in current:
            return None
        current = current[key]
    return current


def validate_one(check: dict[str, Any], strict: bool) -> tuple[bool, str]:
    path = PROJECT_ROOT / check["path"]
    if not path.exists():
        message = f"[MISS] {check['name']}: {check['path']}"
        return (not strict, message)

    try:
        data = read_json(path)
    except Exception as exc:  # noqa: BLE001 - CLI should report exact parser failure.
        return False, f"[FAIL] {check['name']}: JSON parse failed: {exc}"

    values: list[str] = []
    ok = True
    for item in check.get("summary", []):
        label = item[0]
        keys = tuple(item[1])
        default = item[2] if len(item) > 2 else None
        value = dig(data, keys)
        if value is None and default is not None:
            value = default
        if value is None:
            ok = False
            values.append(f"{label}=MISSING")
        else:
            values.append(f"{label}={value}")

    status = "OK" if ok else "FAIL"
    return ok, f"[{status}] {check['name']}: " + ", ".join(values)


def parse_candidate_visual_ids(text: str) -> list[str]:
    visual_ids: list[str] = []
    for line in text.splitlines():
        marker = "  - VisualID:"
        if line.startswith(marker):
            visual_ids.append(line[len(marker) :].strip())
    return visual_ids


def parse_registry_sprite_entries(text: str) -> dict[str, str]:
    entries: dict[str, str] = {}
    lines = text.splitlines()
    for index, line in enumerate(lines[:-1]):
        marker = "  - VisualID:"
        if not line.startswith(marker):
            continue
        visual_id = line[len(marker) :].strip()
        sprite_line = lines[index + 1].strip()
        guid_marker = "guid:"
        if guid_marker not in sprite_line:
            continue
        guid = sprite_line.split(guid_marker, 1)[1].split(",", 1)[0].strip().lower()
        entries[visual_id] = guid
    return entries


def validate_offline_registry_candidate(strict: bool) -> tuple[bool, str]:
    candidate_path = PROJECT_ROOT / OFFLINE_REGISTRY_CANDIDATE
    gap_path = PROJECT_ROOT / REGISTRY_GAP_CHECKLIST
    live_registry_path = PROJECT_ROOT / LIVE_REGISTRY_ASSET
    if not candidate_path.exists():
        message = f"[MISS] offline_registry_candidate: {OFFLINE_REGISTRY_CANDIDATE}"
        return (not strict, message)
    if not gap_path.exists():
        message = f"[MISS] offline_registry_candidate_gap: {REGISTRY_GAP_CHECKLIST}"
        return (not strict, message)

    try:
        candidate_text = candidate_path.read_text(encoding="utf-8-sig")
        gap = read_json(gap_path)
        live_registry_text = live_registry_path.read_text(encoding="utf-8-sig")
    except Exception as exc:  # noqa: BLE001 - CLI should report exact parser failure.
        return False, f"[FAIL] offline_registry_candidate: parse failed: {exc}"

    visual_ids = parse_candidate_visual_ids(candidate_text)
    unique_ids = set(visual_ids)
    gap_items = gap.get("Items", []) if isinstance(gap, dict) else []
    gap_ids = {str(item.get("VisualID", "")) for item in gap_items if isinstance(item, dict)}
    missing_gap_ids = sorted(gap_ids - unique_ids)
    has_missing_sprite = "  MissingSprite: {fileID: 21300000," in candidate_text
    candidate_entries = parse_registry_sprite_entries(candidate_text)
    live_entries = parse_registry_sprite_entries(live_registry_text)
    changed_existing = [
        visual_id
        for visual_id, guid in live_entries.items()
        if candidate_entries.get(visual_id) != guid
    ]

    ok = True
    values = [
        f"candidate_entries={len(visual_ids)}",
        f"unique_entries={len(unique_ids)}",
        f"gap_ids={len(gap_ids)}",
        f"missing_gap_ids={len(missing_gap_ids)}",
        f"has_missing_sprite={has_missing_sprite}",
        f"live_entries={len(live_entries)}",
        f"changed_existing={len(changed_existing)}",
    ]

    if len(visual_ids) != len(unique_ids):
        ok = False
    if missing_gap_ids:
        ok = False
    if not has_missing_sprite:
        ok = False
    if changed_existing:
        ok = False

    status = "OK" if ok else "FAIL"
    return ok, f"[{status}] offline_registry_candidate: " + ", ".join(values)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--strict", action="store_true", help="Treat missing optional outputs as failures.")
    args = parser.parse_args()

    failed = False
    for check in CHECKS:
        ok, message = validate_one(check, strict=args.strict)
        print(message)
        failed = failed or not ok
    ok, message = validate_offline_registry_candidate(strict=args.strict)
    print(message)
    failed = failed or not ok
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
