using System;
using System.IO;
using MCPForUnity.Editor.Helpers;
using Newtonsoft.Json;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace P3.Validation {
[Serializable] public sealed class EditorSnapshot { public bool IsCompiling,IsUpdating,IsPlaying,IsPaused,HasDirtyScenes,HasPrefabStage,PrefabStageDirty;public string ActiveScene,SelectionPath;public static EditorSnapshot Capture(){bool dirty=false;for(int i=0;i<EditorSceneManager.sceneCount;i++)dirty|=EditorSceneManager.GetSceneAt(i).isDirty;var prefab=PrefabStageUtility.GetCurrentPrefabStage();return new EditorSnapshot{IsCompiling=EditorApplication.isCompiling,IsUpdating=EditorApplication.isUpdating,IsPlaying=EditorApplication.isPlaying,IsPaused=EditorApplication.isPaused,HasDirtyScenes=dirty,HasPrefabStage=prefab!=null,PrefabStageDirty=prefab!=null&&prefab.scene.isDirty,ActiveScene=EditorSceneManager.GetActiveScene().path,SelectionPath=Selection.activeObject?AssetDatabase.GetAssetPath(Selection.activeObject):null};}}
[Serializable] public sealed class JobState { public string RunId,Domain,ProfileId,InstanceId,CurrentStep,Status,LastError,StartedAt,UpdatedAt;public float Progress;public bool OriginalPlayMode,OriginalPaused; }
public static class JobStore { static string Key(string id)=>"p3_validation_v2_"+id;public static JobState Load(string id)=>McpJobStateStore.LoadState<JobState>(Key(id));public static void Save(JobState state){state.UpdatedAt=DateTime.UtcNow.ToString("o");McpJobStateStore.SaveState(Key(state.RunId),state);}public static void Clear(string id)=>McpJobStateStore.ClearState(Key(id));}
public static class InstanceLock { [Serializable]sealed class Lock{public string instanceId,runId,updatedAt;}const string Key="p3_validation_v2_instance_lock";public static bool TryAcquire(string instance,string run,out string active){var c=McpJobStateStore.LoadState<Lock>(Key);active=c?.runId;if(c!=null&&c.instanceId==instance&&c.runId!=run){DateTime t;var stale=!DateTime.TryParse(c.updatedAt,out t)||DateTime.UtcNow-t.ToUniversalTime()>TimeSpan.FromMinutes(30);var job=JobStore.Load(c.runId);var terminal=job!=null&&job.Status!="Running";if(!stale&&!terminal)return false;}McpJobStateStore.SaveState(Key,new Lock{instanceId=instance,runId=run,updatedAt=DateTime.UtcNow.ToString("o")});active=run;return true;}public static void Release(string instance,string run){var c=McpJobStateStore.LoadState<Lock>(Key);if(c!=null&&c.instanceId==instance&&c.runId==run)McpJobStateStore.ClearState(Key);}}
public sealed class ConsoleMarker { public string RunId;internal Application.LogCallback Handler;internal System.Collections.Generic.List<object> Entries=new System.Collections.Generic.List<object>();}
public static class ConsoleTracker { public static ConsoleMarker Begin(string runId){var m=new ConsoleMarker{RunId=runId};int n=0;m.Handler=(c,s,t)=>m.Entries.Add(new{log_type=t.ToString(),condition=c,stack_trace=s,occurrence_index=n++,captured_at=DateTime.UtcNow.ToString("o")});Application.logMessageReceived+=m.Handler;return m;}public static string Complete(ConsoleMarker m,ValidationDomain domain){Application.logMessageReceived-=m.Handler;var p=domain==ValidationDomain.Program?EvidencePaths.ForProgramRun(m.RunId):EvidencePaths.ForArtRun(m.RunId);var path=Path.Combine(p.Unity,"console-delta.json");File.WriteAllText(path,JsonConvert.SerializeObject(m.Entries,Formatting.Indented));return path;}}
}
