using System;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

public static class P3UnityValidationOrchestrator {
    private static readonly Dictionary<string,string[]> SmokeSets=new Dictionary<string,string[]>{ {"t0_core",new[]{"PrologueFirstDivePermissionSmokeSuite.Run"}}, {"p0_core",new[]{"ConfigValidationSmokeTest.Run","MainFlowGoldenPathSmokeTest.Run"}} };
    public static object Readiness(){ var s=P3ValidationEditorSnapshot.Capture(); string code=s.HasDirtyScenes?"blocked:dirty_scene":s.PrefabStageDirty?"blocked:dirty_prefab_stage":s.IsCompiling?"validation_limited:UnityEditorCompiling":null; return new { ready=code==null,blocking_code=code,snapshot=s }; }
    public static P3ValidationStepResult RunSmoke(string runId,string profileId,string setId){ if(!SmokeSets.TryGetValue(setId,out var tests)) return P3ValidationStepResult.Blocked(runId,profileId,"smoke",true,"blocked:unregistered_smoke_profile","Unknown smoke profile"); var execution=P3SmokeExecutionService.Execute(tests); var r=execution.Passed?P3ValidationStepResult.Passed(runId,profileId,"smoke",true):P3ValidationStepResult.Failed(runId,profileId,"smoke",true,"smoke_failed",string.Join("; ",execution.Errors)); P3ValidationEvidenceWriter.Write(r); return r; }
    public static P3ValidationJobState Start(string runId,string profileId){ var profile=P3ValidationProfileRegistry.GetRequired(profileId); var snapshot=P3ValidationEditorSnapshot.Capture(); var state=new P3ValidationJobState{RunId=runId,ProfileId=profileId,InstanceId=Application.dataPath,CurrentStep="Preflight",EvidenceRoot=P3ValidationEvidencePaths.ForRun(runId).Root,StartedAt=DateTime.UtcNow.ToString("o"),Status="Running",OriginalPlayMode=snapshot.IsPlaying}; if(!P3ValidationInstanceLock.TryAcquire(state.InstanceId,runId,out var active)){state.Status="Blocked";state.LastError="blocked:unity_validation_job_active:"+active;} else if(snapshot.HasDirtyScenes||snapshot.PrefabStageDirty){state.Status="Blocked";state.LastError="blocked:dirty_editor_state";P3ValidationInstanceLock.Release(state.InstanceId,runId);} else {state.CurrentStep="Execute"; if(!string.IsNullOrEmpty(profile.SmokeSet)){var r=RunSmoke(runId,profileId,profile.SmokeSet); if(r.Status!=P3ValidationStepStatus.Passed){state.Status="Failed";state.LastError=r.Code??r.LimitationCode;}} if(state.Status=="Running"){state.Status="Complete";state.Progress=1;} P3ValidationInstanceLock.Release(state.InstanceId,runId);} P3ValidationJobStore.Save(state); return state; }
}
