using System;
using System.IO;
using System.Security.Cryptography;
using Newtonsoft.Json;
using UnityEngine;

namespace P3.Validation {
public static class ArtAcceptanceAdapter {
 static string ActiveArtRun,ExpectedSourceRun;
 public static void Start(string artRun){if(ProfileRegistry.GetArt("art_regression").Mode!="regression")throw new InvalidOperationException("regression profile unavailable");ArtAcceptanceRunner.AutomatedRunCompleted-=OnRunnerCompleted;ArtAcceptanceRunner.AutomatedRunCompleted+=OnRunnerCompleted;var sourceRun=ArtAcceptanceRunner.BeginAutomatedRun(true);if(string.IsNullOrWhiteSpace(sourceRun)){ArtAcceptanceRunner.AutomatedRunCompleted-=OnRunnerCompleted;throw new InvalidOperationException("art_blocked:regression_runner_busy");}ActiveArtRun=artRun;ExpectedSourceRun=sourceRun;}
 public static void OnRunnerCompleted(string sourceRun,string sourceRoot){if(string.IsNullOrWhiteSpace(ActiveArtRun)||!string.Equals(sourceRun,ExpectedSourceRun,StringComparison.Ordinal))return;Import(ActiveArtRun,ExpectedSourceRun,sourceRun,sourceRoot);ArtValidationOrchestrator.RecordCapture(ActiveArtRun,ArtCaptureRole.Regression);ArtAcceptanceRunner.AutomatedRunCompleted-=OnRunnerCompleted;ActiveArtRun=null;ExpectedSourceRun=null;}
 public static string Import(string artRun,string expectedSourceRun,string sourceRun,string sourceRoot){if(string.IsNullOrWhiteSpace(sourceRun)||string.IsNullOrWhiteSpace(sourceRoot))throw new ArgumentException("art_blocked:regression_source_missing");if(!string.Equals(expectedSourceRun,sourceRun,StringComparison.Ordinal))throw new InvalidOperationException("art_blocked:regression_source_run_mismatch");var names=new[]{"report.json","ui_snapshot.json","registry_snapshot.json","acceptance_checklist.md"};foreach(var n in names)if(!File.Exists(Path.Combine(sourceRoot,n)))throw new FileNotFoundException("art_blocked:regression_artifact_missing:"+n);var screenshotRoot=Path.Combine(sourceRoot,"screenshots");if(!Directory.Exists(screenshotRoot))throw new DirectoryNotFoundException("art_blocked:regression_screenshots_missing");var shots=Directory.GetFiles(screenshotRoot,"*.png",SearchOption.TopDirectoryOnly);if(shots.Length==0)throw new InvalidDataException("art_blocked:regression_screenshots_missing");var dst=Path.Combine(EvidencePaths.ForArtRun(artRun).Root,"regression");Directory.CreateDirectory(dst);foreach(var n in names)File.Copy(Path.Combine(sourceRoot,n),Path.Combine(dst,n),true);var shotDst=Path.Combine(dst,"screenshots");Directory.CreateDirectory(shotDst);var result=new StepResult{ValidationDomain=ValidationDomain.Art,RunId=artRun,ProfileId="art_regression",StepId="regression_import",Required=true,Status=StepStatus.Passed,Code="art_passed:regression_import:"+sourceRun};foreach(var s in shots){var bytes=File.ReadAllBytes(s);if(bytes.Length==0)throw new InvalidDataException("art_blocked:regression_screenshot_empty:"+Path.GetFileName(s));var texture=new Texture2D(2,2);try{if(!texture.LoadImage(bytes)||texture.width<1||texture.height<1)throw new InvalidDataException("art_failed:invalid_regression_png:"+Path.GetFileName(s));}finally{UnityEngine.Object.DestroyImmediate(texture);}var destination=Path.Combine(shotDst,Path.GetFileName(s));File.Copy(s,destination,true);string hash;using(var sha=SHA256.Create())hash=BitConverter.ToString(sha.ComputeHash(bytes)).Replace("-","").ToLowerInvariant();result.Artifacts.Add(new Artifact{Path=destination,SourcePath=s,Sha256=hash,Size=bytes.Length,CapturedAt=File.GetLastWriteTimeUtc(s).ToString("o"),MimeType="image/png"});}var stepDir=Path.Combine(EvidencePaths.ForArtRun(artRun).Steps,"regression_import");Directory.CreateDirectory(stepDir);File.WriteAllText(Path.Combine(stepDir,"result.json"),JsonConvert.SerializeObject(result,Formatting.Indented));return dst;}
}
}
