using System;
using System.IO;
using Newtonsoft.Json;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;

namespace P3.Validation {
[InitializeOnLoad] public static class ArtPlayModeGenerationTracker { const string Key="P3.Validation.ArtPlayModeGeneration";static ArtPlayModeGenerationTracker(){EditorApplication.playModeStateChanged-=OnChanged;EditorApplication.playModeStateChanged+=OnChanged;}static void OnChanged(PlayModeStateChange state){if(state==PlayModeStateChange.EnteredPlayMode)SessionState.SetInt(Key,Current+1);}public static int Current=>SessionState.GetInt(Key,0);}
public static class ArtIterationServiceV2 {
 static string Dir(ArtIterationRequest r){var d=Path.Combine(EvidencePaths.ForArtRun(r.RunId).Iterations,r.IterationId);Directory.CreateDirectory(d);return d;}
 static object Snapshot(ArtIterationRequest r)=>new{run_id=r.RunId,iteration_id=r.IterationId,target_id=r.TargetId,component_path=r.ComponentPath,action=r.Action.ToString(),vector2=new{x=r.Vector2Value.x,y=r.Vector2Value.y},color=new{r=r.ColorValue.r,g=r.ColorValue.g,b=r.ColorValue.b,a=r.ColorValue.a},float_value=r.FloatValue,int_value=r.IntValue,bool_value=r.BoolValue,visual_id=r.VisualId};
 static GameObject ResolveComponent(ArtIterationRequest r){var root=ArtTargetRegistry.ResolveVisibleRoot(r.TargetId);if(string.IsNullOrWhiteSpace(r.ComponentPath)||r.ComponentPath==root.name)return root;var relative=r.ComponentPath.StartsWith(root.name+"/")?r.ComponentPath.Substring(root.name.Length+1):r.ComponentPath;var t=root.transform.Find(relative);if(!t)throw new InvalidOperationException("art_blocked:component_not_registered");return t.gameObject;}
 static void ApplyRuntime(ArtIterationRequest r){var go=ResolveComponent(r);var rt=go.GetComponent<RectTransform>();switch(r.Action){case ArtIterationAction.SetAnchoredPosition:rt.anchoredPosition=r.Vector2Value;break;case ArtIterationAction.SetSizeDelta:rt.sizeDelta=r.Vector2Value;break;case ArtIterationAction.SetAnchorMin:rt.anchorMin=r.Vector2Value;break;case ArtIterationAction.SetAnchorMax:rt.anchorMax=r.Vector2Value;break;case ArtIterationAction.SetSiblingIndex:rt.SetSiblingIndex(r.IntValue);break;case ArtIterationAction.SetColor:go.GetComponent<Graphic>().color=r.ColorValue;break;case ArtIterationAction.SetAlpha:(go.GetComponent<CanvasGroup>()??go.AddComponent<CanvasGroup>()).alpha=r.FloatValue;break;case ArtIterationAction.SetCanvasGroup:var cg=go.GetComponent<CanvasGroup>()??go.AddComponent<CanvasGroup>();cg.blocksRaycasts=r.BoolValue;cg.interactable=r.BoolValue;break;case ArtIterationAction.SetRaycastTarget:go.GetComponent<Graphic>().raycastTarget=r.BoolValue;break;case ArtIterationAction.SetTextStyle:go.GetComponent<Text>().fontSize=r.IntValue;break;case ArtIterationAction.BindApprovedVisualId:throw new InvalidOperationException("art_blocked:visual_binding_requires_registered_adapter");}}
 public static ArtIterationResult Preview(ArtIterationRequest r){ArtTargetRegistry.Get(r.TargetId);ApplyRuntime(r);var result=new ArtIterationResult{RunId=r.RunId,IterationId=r.IterationId,TargetId=r.TargetId,Mode="preview",Status="Previewed",SatisfiesFormalValidation=false};File.WriteAllText(Path.Combine(Dir(r),"preview-changes.json"),JsonConvert.SerializeObject(Snapshot(r),Formatting.Indented));return result;}
 public static ArtIterationResult Persist(ArtIterationRequest r){ArtTargetRegistry.Get(r.TargetId);if(r.Action==ArtIterationAction.BindApprovedVisualId&&string.IsNullOrWhiteSpace(r.VisualId))throw new InvalidOperationException("art_blocked:visual_id_not_registered");var persisted=ArtPersistAdapterRegistry.Get(r.TargetId).Apply(r);if(!persisted.Changed)throw new InvalidOperationException("art_blocked:persist_no_change");var s=ArtValidationOrchestrator.Load(r.RunId);s.HasPersistedChanges=true;s.HasPostPersistInspection=false;s.PersistedPlayModeGeneration=ArtPlayModeGenerationTracker.Current;s.Status="AwaitingPlayModeReload";File.WriteAllText(Path.Combine(EvidencePaths.ForArtRun(r.RunId).Root,"session.json"),JsonConvert.SerializeObject(s,Formatting.Indented));File.WriteAllText(Path.Combine(Dir(r),"persisted-changes.json"),JsonConvert.SerializeObject(new{request=Snapshot(r),result=persisted},Formatting.Indented));return new ArtIterationResult{RunId=r.RunId,IterationId=r.IterationId,TargetId=r.TargetId,Mode="persist",DurableSource=persisted.DurableSource,Status="Persisted",SatisfiesFormalValidation=false};}
 public static ArtIterationResult Complete(ArtIterationRequest r){var s=ArtValidationOrchestrator.Load(r.RunId);if(!s.HasPersistedChanges||!s.RecordedRoles.Contains("before")||!s.RecordedRoles.Contains("after")||!s.HasPostPersistInspection)throw new InvalidOperationException("art_blocked:playmode_reload_and_reinspect_required");var result=new ArtIterationResult{RunId=r.RunId,IterationId=r.IterationId,TargetId=r.TargetId,Mode="complete",Status="EvidenceReady",SatisfiesFormalValidation=true};File.WriteAllText(Path.Combine(Dir(r),"result.json"),JsonConvert.SerializeObject(result,Formatting.Indented));return result;}
}
}
